# Generated by Django 4.1.5 on 2023-01-27 22:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuscontent',
            name='information',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
