# Generated by Django 4.1.5 on 2023-01-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchResults', '0009_category_rename_name_jobcategory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcategory',
            old_name='category',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='searchResults.jobcategory'),
        ),
    ]
