# Generated by Django 4.1.5 on 2023-01-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_services_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.AlterModelTable(
            name='services',
            table=None,
        ),
    ]
