# Generated by Django 4.1.5 on 2023-01-30 21:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_alter_aboutuscontent_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuscontent',
            name='information',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
