# Generated by Django 4.1.5 on 2023-01-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
