# Generated by Django 4.1.5 on 2023-01-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_jobs_thumbnail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='services',
            table='Services',
        ),
    ]
