# Generated by Django 4.1.5 on 2023-01-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_services_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='tagline',
            field=models.CharField(default='', max_length=20),
        ),
    ]
