# Generated by Django 4.1.5 on 2023-01-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_jobs_alter_services_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
