# Generated by Django 4.1.5 on 2023-01-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchResults', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
