# Generated by Django 4.1.5 on 2023-01-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchResults', '0004_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
