# Generated by Django 4.1.5 on 2023-01-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchResults', '0005_rename_category_categorie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
