# Generated by Django 4.1.5 on 2023-01-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchResults', '0010_rename_category_jobcategory_name_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default='categorized', on_delete=django.db.models.deletion.CASCADE, to='searchResults.jobcategory'),
        ),
    ]
