# Generated by Django 4.1.5 on 2023-01-27 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='home_user',
        ),
    ]
