# Generated by Django 4.1.5 on 2023-02-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchResults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
