# Generated by Django 4.1.5 on 2023-02-02 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchResults', '0003_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
