# Generated by Django 4.1.5 on 2023-02-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchResults', '0002_alter_job_title_alter_jobcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
